package org.knt;
/*
 * This class is a simple calculator that can add, subtract, multiply, and divide two integers.
 * It was generated by Cursor.
 */
public class Calc {
    public int add(int a, int b) {
        return a + b;
    }

    public int subtract(int a, int b) {
        return a - b;
    }

    public int multiply(int a, int b) {
        return a * b;
    }

    public int divide(int a, int b) {
        return a / b;
    }   
}
